# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# climate__raster.py
# Created on: 2018-01-10 10:04:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: climate__raster <Z_value_field> <output> <X_Field> <Y_Field> <HadGEM_2006_2050_csv> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os

print "imported"

#set workspace
arcpy.env.workspace = "R:\\Streletskiy Research\\Luis_Files\\Thesis\\GCM_Results\\CSVs"
arcpy.env.overwriteOutput = True
print "workspace set"


files = arcpy.ListFiles("*.csv")
print files

Z_value_field = ["ta", "h_snow", "fu", "magt", "altr", "pr", "fdi", "ftc", "w_road", "heat"]
X_Field = "lat"
Y_Field = "lon"
spRef  = arcpy.SpatialReference(4326) #WGS1984
xy_output = "temp_layer"

print Z_value_field
print "variables set"

#still having some issues with the save_file.... ".csv" at the end of file names is messing up the save, how do I truncate it?
def climate_raster(x,y):
	for xs in x:
		arcpy.MakeXYEventLayer_management(xs, X_Field, Y_Field, xy_output, spRef)
		for ys in y:
			save_file = "R:\\Streletskiy Research\\Luis_Files\\Thesis\GCM_Results\\TIFFs\\2006_2050\\%s_%s" %(xs[0:10], ys)
			arcpy.gp.NaturalNeighbor_sa(xy_output, ys, save_file, "R:\\Streletskiy Research\\Luis_Files\\Thesis\\GIS\\Rasterization_Files\\half_deg")
			print "Done %s %s" %(xs, ys)
	print "Done All"

climate_raster(files, Z_value_field)
			
print "Process Complete"
	




