# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# climate__raster.py
# Created on: 2018-01-10 10:04:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: climate__raster <Z_value_field> <output> <X_Field> <Y_Field> <HadGEM_2006_2050_csv> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os

print "imported"

#set workspace
arcpy.env.workspace = "R:\\Streletskiy Research\\Luis_Files\\Thesis\GIS\\Geodatabases\\Arctic_ERA.gdb"
arcpy.env.overwriteOutput = True
print "workspace set"

# list point (port, airport, settlement) features and rasterize them into 1x1 cells with sum of points as value
for file in arcpy.ListFeatureClasses(feature_type='Point'):
	#reproject to WGS84 for rasterization
	coord = arcpy.SpatialReference(4326) #WGS 1984
	proj_file = arcpy.Project_management(file, "temp", coord)
	print "%s reprojected" %(file[0:12])
	#convert points to raster and save to new file
	save_file = "R:\\Streletskiy Research\\Luis_Files\\Thesis\\GIS\\Arctic_ERA_Rasters\\%s" %(file[0:12])
	cellsize = "R:\\Streletskiy Research\\Luis_Files\\Thesis\\GIS\\Rasterization_Files\\1x1_standard"
	arcpy.PointToRaster_conversion (proj_file,"", save_file, "COUNT","",cellsize)
	arcpy.Delete_management("temp")
	print "Done %s" %(file)
	
	
#list lines (road, rail, pipeline), split them by their intersections with 1x1 grid (to account for double counting)
# then rasterize them with the shape length as the value
for file in arcpy.ListFeatureClasses(feature_type='Line'):
	intersect_poly =  "R:\Streletskiy Research\\Luis_Files\\Thesis\\GIS\\Rasterization_Files\\1x1_fishnet.shp"
	save_file = "R:\Streletskiy Research\Luis_Files\Thesis\GIS\Arctic_ERA_Rasters\%s" %(file[0:12])
	split_file = "split_%s" %(file)
	coord = arcpy.SpatialReference(4326) #WGS 1984
	proj_file = arcpy.Project_management(file, "temp", coord)
	#find intersections between lines and cell edges
	arcpy.Intersect_analysis([file, intersect_poly], "temp_layer", "", "", "point")
	#split line at these points
	cellsize = "R:\\Streletskiy Research\\Luis_Files\\Thesis\\GIS\\Rasterization_Files\\1x1_standard"
	arcpy.SplitLineAtPoint_management(file, "temp_layer", split_file, "50 Meters")
	arcpy.PolylineToRaster_conversion(split_file, "Shape_Length", save_file,"MAXIMUM_COMBINED_LENGTH", "", cellsize)
	arcpy.Delete_management(split_file)
	arcpy.Delete_management("temp_layer")
	print "Done %s"%(file)
	
print "infrastructure rasterized"

